import './globals.css'
import ClientWrapper from "@/assets/components/ClientWrapper"; // Adjust the path as needed


export const metadata = {
  title: 'Canvas',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
    <body>
      <ClientWrapper>
        {children}
      </ClientWrapper>
    </body>
  </html>
  )
}
